runtime: python27
version: 1
api_version: 1
application: strife-drafter
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html
  secure: always

- url: /static
  static_dir: static
  secure: always

includes:
- cosmopolite

inbound_services:
- channel_presence
